publishDir = "docs/"
baseURL = "https://shahadarsh.github.io/docker-k8s-presentation/"
languageCode = "en-us"
title = "Introduction to Kubernetes"
theme = "learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "mine"

